name: Kernel build CI test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jiu-xiao/kernel-docker:main

    steps:
    - uses: actions/checkout@v3
    - name: create shit dir
      run: mkdir drivers/input/touchscreen/focaltech_3658u/include && mkdir drivers/input/touchscreen/focaltech_touch/include

    - name: change full capacity
      run: sed -i '736s/.*/	*nom_cap_uah = ${{ vars.capacity }} *1000;/' drivers/power/supply/qcom/qpnp-fg-gen4.c


    - name: change design full capacity
      run: sed -i '28s/.*/	qcom,nom-batt-capacity-mah = < ${{ vars.capacity }} >;/' arch/arm64/boot/dts/vendor/qcom/fg-gen4-batterydata-alioth-FMT-4520mah.dtsi

    - name: prebuild
      run: bash compile.sh
    - name: build
      run: bash compile-alioth.sh
    - name: pack kernel
      run: cp out/outputs/alioth/Image.gz ./F3-NoGravityKernel-1.5.0/ && cp out/outputs/alioth/dtb ./F3-NoGravityKernel-1.5.0/ && cp out/outputs/alioth/alioth_dtbo-miui.img ./F3-NoGravityKernel-1.5.0/ && mv ./F3-NoGravityKernel-1.5.0/alioth_dtbo-miui.img ./F3-NoGravityKernel-1.5.0/dtbo.img && cd F3-NoGravityKernel-1.5.0 && zip -r alioth-${{ vars.capacity }}.zip ./*

    - name: Create release
      run: echo "release_name=$(date +v%Y.%m.%d.vv%H.%M)" >> $GITHUB_ENV

    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.release_name }}
          release_name: Release ${{ env.release_name }}
          draft: false
          prerelease: false

    - name: Upload Kernel
      uses: actions/upload-release-asset@v1
      id: upload-kernel
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/F3-NoGravityKernel-1.5.0/alioth-${{ vars.capacity }}.zip
        asset_name: alioth-${{ vars.capacity }}.zip
        asset_content_type: application/zip
