name: Kernel build CI

on:
  workflow_dispatch:
  push:
    branches: [ "t-caf" ]
  pull_request:
    branches: [ "t-caf" ]

jobs:
  build:

    runs-on: ghcr.io/jiu-xiao/kernel-docker:main

    steps:
    - uses: actions/checkout@v3
    - name: create shit dir
      run: mkdir drivers/input/touchscreen/focaltech_3658u/include && mkdir drivers/input/touchscreen/focaltech_touch/include
    - name: prebuild
      run: bash compile.sh
    - name: build
      run: bash compile-alioth.sh
    - name: pack kernel
      run: cp out/outputs/alioth/Image.gz ./F3-NoGravityKernel-1.5.0/ && cp out/outputs/alioth/dtb ./F3-NoGravityKernel-1.5.0/ && cp out/outputs/alioth/alioth_dtbo-miui.img ./F3-NoGravityKernel-1.5.0/ && mv ./F3-NoGravityKernel-1.5.0/alioth_dtbo-miui.img ./F3-NoGravityKernel-1.5.0/dtbo.img && cd F3-NoGravityKernel-1.5.0 && zip -r alioth.zip ./*

    - name: Create release
      run: echo "release_name=$(date +v%Y.%m.%d.vv%H.%M)" >> $GITHUB_ENV

    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.release_name }}
          release_name: Release ${{ env.release_name }}
          draft: false
          prerelease: false

    - name: Upload Kernel
      uses: actions/upload-release-asset@v1
      id: upload-kernel
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/F3-NoGravityKernel-1.5.0/alioth.zip
        asset_name: alioth.zip
        asset_content_type: application/zip
